descriptor-schema-version: "2.0"

info:
  name: KineticPi
  description: "IOx Java PaaS style Application to demonstrate DCM Rule Engine on Edge functionality, utilizing Raspberry Pi with Sense HAT module as a sensor"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  type: paas

  resources:
      profile: c1.medium
      cpu: 400
      memory: 128
      network:
        -
          interface-name: eth0
          ports:
            tcp:
            - 8883

  startup:
    runtime: java-se-embedded-cp3
    runtime-version: 1.8
    runtime-options:
      classpath: "$CAF_APP_PATH/"
    target: launch.sh
